language: php
before_script:
- composer self-update
- composer install --dev --no-interaction
#- phpenv local --unset
script:
- vendor/bin/phpunit --coverage-clover clover.xml
after_script:
#- cd ..
#- phpenv local 5.5
#- phpenv local --unset
php:
- 5.5
- 5.6
- 7.0
notifications:
  email: false
